# Generated by Django 5.0.3 on 2024-03-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='CustomerName',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
