# Generated by Django 5.0.3 on 2024-03-17 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoice_customername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicedetail',
            old_name='Invoice',
            new_name='invoice',
        ),
    ]
