# Generated by Django 5.0.3 on 2024-03-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_rename_invoice_invoicedetail_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='description',
            field=models.CharField(max_length=512),
        ),
    ]
